<?php
global $db;
$userManager = new UserManager($db);
?>

<div class="room-heading">
   <h1><?= $data['room']->getName(); ?></h1>
</div>
<div class="room-chat">
   <section aria-labelledby="srt-feed">
      <h2 class="visually-hidden" id="srt-feed">Feed</h2>
      <div role="feed">
         <?php foreach ($data['messages'] as $msg) { ?>
            <article>
               <header>
                  <h3><?= $userManager->getUserById($msg['user_id'])->getUsername(); ?></h3>
                  <div><?php
                        $msg['creation_date'];
                        ?></div>
               </header>
               <p class="message-content">
                  <?php $msg['content'] ?>
               </p>
            </article>
         <?php } ?>
      </div>
   </section>
   <section>
      <form action="index.php?route=chat-sendmessage" method="POST">
         <input type="hidden" name="category_id" value="<?= $data['category']->getId(); ?>">
         <input type="hidden" name="room_id" value="<?= $data['room']->getId(); ?>">
         <label for="messageContent" class="visually-hidden">Message <?= $data['room']->getName(); ?></label>
         <div class="message-input-wrapper">
            <input type="text" name="content" id="messageContent" placeholder="Message <?= $data['room']->getName(); ?>">
            <button aria-label="Send message">
               Envoyer
            </button>
         </div>
      </form>
   </section>
</div>