<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Le titre à dynamiser</title>
</head>

<body>
   <?php if (isset($_SESSION["user_id"])) { ?>
      <header>
         <div>
            <a href="">Categories</a>
         </div>
         <div>
            <div><!-- truc à cliquer jspkoi --></div>
            <nav>
               <ul>
                  <li><a href="index.php?route=user-logout">Log out</a></li>
               </ul>
            </nav>
         </div>
      </header>
   <?php } ?>
   <main>
      require $template
   </main>

   <footer>

   </footer>
</body>

</html>