<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Le titre à dynamiser</title>
   <!-- ajout temporaire bootstrap ici -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</head>

<body>
   <?php if (isset($_SESSION["user_id"])) { ?>
      <header>
         <div>
            <a href="">Categories</a>
         </div>
         <div>
            <div><!-- truc à cliquer jspkoi --></div>
            <nav>
               <ul>
                  <li><a href="index.php?route=user-logout">Log out</a></li>
               </ul>
            </nav>
         </div>
      </header>
   <?php } ?>
   <main>
      <?php require $template ?>
   </main>

   <footer>

   </footer>
</body>

</html>