<div class="login-container">
   <form action="index.php?route=login">
      <div>
         <label for="email">Email</label>
         <input type="text" class="form-control" name="email" id="email">
      </div>
      <div>
         <label for="password">Password</label>
         <input type="text" class="form-control" name="password" id="password">
      </div>
      <div>
         <button class="btn btn-primary">Log in</button>
      </div>
   </form>
</div>