<div class="login-container">
   <form action="index.php?route=user-login" method="POST">
      <div>
         <label for="email">Email</label>
         <input type="email" class="form-control" name="email" id="email">
      </div>
      <div>
         <label for="password">Password</label>
         <input type="password" class="form-control" name="password" id="password">
      </div>
      <div>
         <button type="submit" class="btn btn-primary">Log in</button>
      </div>
   </form>
   <nav>
      <ul>
         <li><a href="index.php?route=user-register">Sign up</a></li>
         <li class="current">Log in</li>
      </ul>
   </nav>
</div>