<div class="register-container">
   <form action="index.php?route=user-register" method="POST">
      <div>
         <label for="username">Username</label>
         <input type="text" class="form-control" name="username" id="username">
      </div>
      <div>
         <label for="email">Email</label>
         <input type="text" class="form-control" name="email" id="email">
      </div>
      <div>
         <label for="password">Password</label>
         <input type="text" class="form-control" name="password" id="password">
      </div>
      <div>
         <label for="confirm-password">Confirm password</label>
         <input type="text" class="form-control" name="confirm-password">
      </div>
      <div>
         <button class="btn btn-primary">Sign Up</button>
      </div>
   </form>
   <nav>
      <ul>
         <li class="current">Sign up</li>
         <li><a href="index.php?route=user-login">Log in</a></li>
      </ul>
   </nav>
</div>